<a href="https://colab.research.google.com/github/dngtundt/THDL_Buoi1/blob/main/THDL_Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3.1.
Tạo array 1 chiều

In [ ]:
import numpy as np

# cách 1
# tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)

# chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


3.2. Array 2-chiều

In [ ]:
c = np.array([(1, 2, 3),
              (4, 5, 6)])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


3.3. Array 3-chiều

In [ ]:
d = np.array([
              [[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10, 11, 12]]
            ])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [ ]:
e = np.zeros((2, 2))
f = np.ones((3, 3))

print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3.5.1. Reshape thay đổi kích thước ma trận

In [ ]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


TENSOR

3.1 Tensor 1 chiều

In [ ]:
import tensorflow as tf
# Mặc định là int32
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

# Tạo tensor scalar với các kiểu dữ liệu khác nhau
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


 3.2 Tensor 1-chiều (Vector)

In [ ]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


3.3. Tensor 2-chiều (Ma trận)

In [ ]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


3.4. Tensor n-chiều (Ví dụ Tensor 3-chiều)

In [ ]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]]
])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


3.5. Thuộc tính của Tensor

In [ ]:
print('\nShape:', rank_3_tensor.shape)
print('Type of tensor:', rank_3_tensor.dtype)


Shape: (3, 2, 5)
Type of tensor: <dtype: 'int32'>


3.6. Tạo tensor tự động gán giá trị 0

In [ ]:
t_zero = tf.zeros(10)
print("\nZeros 1D:\n", t_zero)


Zeros 1D:
 tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [ ]:
# 1. Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0
t1 = tf.zeros([2, 3])
print("1. Tensor [2, 3] toàn số 0:\n", t1)

1. Tensor [2, 3] toàn số 0:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
# 2. Cho X = [[1, 2, 3], [4, 5, 6]], tạo tensor kích thước và dtype như X gán 0
X = [[1, 2, 3], [4, 5, 6]]
t2 = tf.zeros_like(X)
print("\n2. Tensor zeros_like X:\n", t2)


2. Tensor zeros_like X:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [ ]:
# 3. Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5
t3 = tf.fill([3, 2], 5)
print("\n3. Tensor [3, 2] toàn số 5:\n", t3)


3. Tensor [3, 2] toàn số 5:
 tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


In [ ]:
# 4. Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]
# Khoảng [5, 10] số chẵn 6, 8, 10.
# Giả sử 50 giá trị cách đều nhau:
t4 = tf.linspace(6.0, 10.0, 50)
print("\n4. Tensor 1D 50 phần tử từ 6 đến 10:\n", t4)


4. Tensor 1D 50 phần tử từ 6 đến 10:
 tf.Tensor(
[ 6.         6.0816326  6.163265   6.244898   6.3265305  6.408163
  6.4897957  6.5714283  6.6530614  6.734694   6.8163266  6.897959
  6.979592   7.0612245  7.142857   7.2244897  7.3061223  7.387755
  7.469388   7.5510206  7.632653   7.714286   7.7959185  7.877551
  7.9591837  8.040816   8.122449   8.204082   8.285714   8.367347
  8.448979   8.530612   8.612245   8.693877   8.77551    8.857142
  8.938776   9.020409   9.102041   9.183674   9.265306   9.346939
  9.428572   9.510204   9.591837   9.67347    9.755102   9.836735
  9.918367  10.       ], shape=(50,), dtype=float32)


In [ ]:
# 5. Tạo một tensor 1-chiều có giá trị [10, 12, 14, …, 100]
t5 = tf.range(start=10, limit=101, delta=2)
print("\n5. Tensor cấp số cộng từ 10 đến 100:\n", t5)


5. Tensor cấp số cộng từ 10 đến 100:
 tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


In [ ]:
# 6. Tensor [3, 2] ngẫu nhiên phân phối Normal (mean=0, stddev=2)
t6 = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)
print("\n6. Tensor Normal distribution:\n", t6)


6. Tensor Normal distribution:
 tf.Tensor(
[[ 1.5710286   1.0879055 ]
 [-1.2583251  -0.29601362]
 [ 0.3748432  -0.27572542]], shape=(3, 2), dtype=float32)


In [ ]:
# 7. Tensor [3, 2] ngẫu nhiên phân phối Uniform trong phạm vi [0, 2]
t7 = tf.random.uniform(shape=[3, 2], minval=0, maxval=2)
print("\n7. Tensor Uniform distribution:\n", t7)


7. Tensor Uniform distribution:
 tf.Tensor(
[[0.18302989 1.2750237 ]
 [0.11653614 0.7225001 ]
 [1.5132568  1.4997282 ]], shape=(3, 2), dtype=float32)


In [ ]:
import tensorflow as tf

In [ ]:
# 8. Shuffle X theo chiều thứ nhất
X = tf.constant([[1, 2], [3, 4], [5, 6]])
# tf.random.shuffle sẽ xáo trộn các hàng
shuffled_X = tf.random.shuffle(X)
print("8. X sau khi shuffle hàng:\n", shuffled_X)

8. X sau khi shuffle hàng:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
# 9. Tạo tensor (10, 10, 3) và cắt thành (5, 5, 3)
# Giả lập một ảnh 10x10
original_tensor = tf.random.uniform(shape=(10, 10, 3), minval=0, maxval=255, dtype=tf.int32)
cropped_tensor = tf.image.random_crop(original_tensor, size=[5, 5, 3])
print("\n9. Kích thước sau khi crop:", cropped_tensor.shape)


9. Kích thước sau khi crop: (5, 5, 3)


In [ ]:
# 10. Logic điều kiện trên hai tensor x, y
x = tf.random.uniform(shape=[5], minval=0, maxval=10)
y = tf.random.uniform(shape=[5], minval=0, maxval=10)
result_10 = tf.where(x < y, x + y, x - y)
print("\n10. Tensor x:", x.numpy())
print("    Tensor y:", y.numpy())
print("    Kết quả (x+y nếu x<y, ngược lại x-y):\n", result_10.numpy())


10. Tensor x: [0.18731356 9.272395   7.5941396  7.368777   9.362097  ]
    Tensor y: [4.6105456 3.6718225 1.6878128 7.9721212 6.8859434]
    Kết quả (x+y nếu x<y, ngược lại x-y):
 [ 4.797859   5.6005726  5.906327  15.3408985  2.4761534]


In [ ]:
# 11. Phép toán ma trận và đường chéo
x_11 = tf.random.uniform(shape=(3, 2), minval=5, maxval=10)
y_11 = tf.random.uniform(shape=(2, 3), minval=15, maxval=20)

# x + y chỉ thực hiện được khi cùng kích thước.
# x (3,2) và y (2,3) khác kích thước
# Chuyển vị
y_transposed = tf.transpose(y_11)
sum_result = x_11 + y_transposed

# Lấy đường chéo của x
diag_x = tf.linalg.diag_part(x_11)

print("\n11. Đường chéo của x:", diag_x.numpy())
print("    Kết quả x + y_T:\n", sum_result.numpy())


11. Đường chéo của x: [8.245333  6.1015487]
    Kết quả x + y_T:
 [[23.951748 26.856071]
 [22.044735 22.319681]
 [24.679333 26.697657]]
