<a href="https://colab.research.google.com/github/dngtundt/THDL_Buoi1/blob/main/THDL_Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3.1.
Tạo array 1 chiều

In [ ]:
import numpy as np

# cách 1
# tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)

# chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


3.2. Array 2-chiều

In [2]:
c = np.array([(1, 2, 3),
              (4, 5, 6)])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


3.3. Array 3-chiều

In [3]:
d = np.array([
              [[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10, 11, 12]]
            ])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [4]:
e = np.zeros((2, 2))
f = np.ones((3, 3))

print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
